In [10]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.optim as optim
import torch.utils.data
from torch.autograd import Variable

In [12]:
data = pd.read_csv('s1_improvised.csv', header = None, engine = 'python', encoding = 'latin-1')
data.dropna(axis=0, how="all", thresh=None, subset=None, inplace=True)

data

0      1             2      3                4         5   \
0   NO.  MA101  ma_internals  PH100  ph100_internals   BE10105   
1     1    0.0            25      0               23       0.0   
2     2    6.0            41      7               46       7.0   
3     3   10.0            47     10               50       6.0   
4     5    6.0            31      9               41       5.0   
5     6   10.0            45      7               46       0.0   
6     7    9.0            46      9               47       8.0   
7     8    5.0            25      6               40       0.0   
8     9    6.0            31      6               34       5.0   
9    10    0.0            24      4               24       0.0   
10   11    9.0            43     10               47       6.0   
11   12    6.0            36      6               39       5.0   
12   13    6.0            33      9               42       8.0   
13   15    9.0            48      7               45       8.0   
14   16   10.0            44     10               49       9.0   
15   17    7.0            46      9               46       8.0   
16   19    7.0            43      7               38       6.0   
17   20    7.0            42      6               48       9.0   
18   21    0.0            30      6               38       0.0   
19   22   10.0            44      8               42       7.0   
20   23    7.0            36      8               47       9.0   
21   25    0.0            27      6               27       0.0   
22   26    8.0            48      9               43       7.0   
23   28    0.0            27      0               29       0.0   
24   30    6.0            41      7               43       6.0   
25   31    0.0            33      5               39       0.0   
26   33    8.0            45      6               39       0.0   
27   34    0.0            23      0               27       7.0   
28   35    5.0            32      5               34       6.0   
29   36    5.0            32      6               36       5.0   
30   37    9.0            45      7               50       0.0   
31   38    6.0            37      7               50       8.0   
32   39   10.0            45      8               43       0.0   
33   40    7.0            38      7               42       5.0   
34   41    0.0            23      4               26       0.0   
35   42    8.0            46      7               45       6.0   
36   43    7.0            43      6               42       5.0   
37   44    7.0            46      9               47       8.0   
38   45    7.0            46      7               39       8.0   
39   46    0.0            26      0               35       9.0   
40   48    6.0            40      7               49       8.0   
41   49    5.0            29      6               29       0.0   
42   50    0.0            24      0               30       0.0   
43   51    0.0            26      0               29       0.0   
44   52    8.0            41      9               44       5.0   
45   53    7.0            46      8               46       9.0   
46   54    7.0            39      7               43       6.0   
47   55    6.0            37      5               39       5.0   
48   56   10.0            50     10               48       7.0   
49   57    8.0            45      8               46       7.0   
50   58    5.0            33      6               36       5.0   
51   59    0.0            26      5               39       5.0   
52   60    5.0            36      6               33       0.0   
53   61    6.0            31      4               25       0.0   
54   62    0.0            27      0               25       5.0   

                   6      7                8       9                10  \
0   be10105_internals  BE110  be110_internals   BE103  be103_internals   
1                  35      8               96       5               36   
2                  47      7               92       7               40   
3           

In [20]:
x=pd.read_csv('s1_train.csv')
x

NO.  MA101  PH100   BE10105  BE110   BE103   EC100   PH110   EC110   CS110
0    12    6.0      6       5.0      6       6       0      10       8      10
1    36    5.0      6       5.0      6       7       0      10       9       9
2    28    0.0      0       0.0      0       7       0       9       7       8
3    39   10.0      8       0.0     10       8       7      10      10       9
4    46    0.0      0       9.0      6       6       0      10       8       9
5    45    7.0      7       8.0      8       6       0      10      10      10
6     9    6.0      6       5.0      0       6       5      10      10      10
7    17    7.0      9       8.0     10       8       6      10      10      10
8    35    5.0      5       6.0      7       7       6       9      10       9
9    43    7.0      6       5.0      9       7       6      10       9       9
10   58    5.0      6       5.0      7       6       0      10      10       8
11   22   10.0      8       7.0      9       6       7       9       8      10
12   60    5.0      6       0.0      7       6       5      10      10       9
13   42    8.0      7       6.0      7       7       7      10      10      10
14   19    7.0      7       6.0     10       7       7       9       8      10
15    7    9.0      9       8.0      8       8       9      10      10      10
16   37    9.0      7       0.0      8       7       9      10      10       9
17   20    7.0      6       9.0     10       8       6       9      10      10
18   55    6.0      5       5.0      7       6       6      10      10      10
19   25    0.0      6       0.0      6       7       5       9       7       9
20   61    6.0      4       0.0      0       5       0       9       7       8
21   10    0.0      4       0.0      7       7       0       8       8      10
22   16   10.0     10       9.0     10       8       8      10       9      10
23   33    8.0      6       0.0      0       9       5       9       9      10
24   21    0.0      6       0.0      0       6       0      10       9      10
25   49    5.0      6       0.0      7       7       0       9       9      10
26   52    8.0      9       5.0      9       7       8      10      10      10
27    2    6.0      7       7.0      7       7       0      10       9      10
28   15    9.0      7       8.0     10       7       0      10       8      10
29   50    0.0      0       0.0      0       7       0       9       8      10
30   31    0.0      5       0.0      6       8       0       9      10       7
31    8    5.0      6       0.0      0       7       0      10       9      10
32   30    6.0      7       6.0      8       7       5      10       9      10
33   44    7.0      9       8.0      7       7       7      10       9       9
34   26    8.0      9       7.0      9       8       9      10      10      10
35   23    7.0      8       9.0     10       8       7      10      10      10
36   11    9.0     10       6.0      8       9       7      10      10      10
37   48    6.0      7       8.0      0       6       6      10       9       8
38   59    0.0      5       5.0      6       7       0      10       9       9
39    5    6.0      9       5.0      7       9       7      10      10       9
40    1    0.0      0       0.0      8       5       0       9       9       7
41   56   10.0     10       7.0      9       6       6      10      10      10
42   53    7.0      8       9.0      7       8       6      10      10      10

In [13]:
training_set = pd.read_csv('s1_train.csv')
training_set = np.array(training_set, dtype = 'int')
test_set = pd.read_csv('s1_test.csv')
test_set = np.array(test_set, dtype = 'int') 

In [14]:
print(training_set)

[[12  6  6  5  6  6  0 10  8 10]
 [36  5  6  5  6  7  0 10  9  9]
 [28  0  0  0  0  7  0  9  7  8]
 [39 10  8  0 10  8  7 10 10  9]
 [46  0  0  9  6  6  0 10  8  9]
 [45  7  7  8  8  6  0 10 10 10]
 [ 9  6  6  5  0  6  5 10 10 10]
 [17  7  9  8 10  8  6 10 10 10]
 [35  5  5  6  7  7  6  9 10  9]
 [43  7  6  5  9  7  6 10  9  9]
 [58  5  6  5  7  6  0 10 10  8]
 [22 10  8  7  9  6  7  9  8 10]
 [60  5  6  0  7  6  5 10 10  9]
 [42  8  7  6  7  7  7 10 10 10]
 [19  7  7  6 10  7  7  9  8 10]
 [ 7  9  9  8  8  8  9 10 10 10]
 [37  9  7  0  8  7  9 10 10  9]
 [20  7  6  9 10  8  6  9 10 10]
 [55  6  5  5  7  6  6 10 10 10]
 [25  0  6  0  6  7  5  9  7  9]
 [61  6  4  0  0  5  0  9  7  8]
 [10  0  4  0  7  7  0  8  8 10]
 [16 10 10  9 10  8  8 10  9 10]
 [33  8  6  0  0  9  5  9  9 10]
 [21  0  6  0  0  6  0 10  9 10]
 [49  5  6  0  7  7  0  9  9 10]
 [52  8  9  5  9  7  8 10 10 10]
 [ 2  6  7  7  7  7  0 10  9 10]
 [15  9  7  8 10  7  0 10  8 10]
 [50  0  0  0  0  7  0  9  8 10]
 [31  0  5

In [34]:
nb_students = int(max(max(training_set[:,0]), max(test_set[:,0])))
nb_courses = max(training_set.shape[1], test_set.shape[1])-1


In [39]:
# def convert(data):
#     new_data = []
#     for id_users in range(1, no_students + 1):
#         id_courses = data[:,1][data[:,0] == id_users]
#         id_ratings = data[:,2][data[:,0] == id_users]
#         ratings = np.zeros(no_movies)
#         print(ratings)
#         print(ratings.size)
#         ratings[id_courses - 1] = id_ratings
#         print(ratings)
#         print(ratings.size)
#         new_data.append(list(ratings))
#     return new_data

In [35]:
training_set = torch.FloatTensor(training_set)
test_set = torch.FloatTensor(test_set)

In [36]:
print(training_set)
print(test_set)

tensor([[12.,  6.,  6.,  5.,  6.,  6.,  0., 10.,  8., 10.],
        [36.,  5.,  6.,  5.,  6.,  7.,  0., 10.,  9.,  9.],
        [28.,  0.,  0.,  0.,  0.,  7.,  0.,  9.,  7.,  8.],
        [39., 10.,  8.,  0., 10.,  8.,  7., 10., 10.,  9.],
        [46.,  0.,  0.,  9.,  6.,  6.,  0., 10.,  8.,  9.],
        [45.,  7.,  7.,  8.,  8.,  6.,  0., 10., 10., 10.],
        [ 9.,  6.,  6.,  5.,  0.,  6.,  5., 10., 10., 10.],
        [17.,  7.,  9.,  8., 10.,  8.,  6., 10., 10., 10.],
        [35.,  5.,  5.,  6.,  7.,  7.,  6.,  9., 10.,  9.],
        [43.,  7.,  6.,  5.,  9.,  7.,  6., 10.,  9.,  9.],
        [58.,  5.,  6.,  5.,  7.,  6.,  0., 10., 10.,  8.],
        [22., 10.,  8.,  7.,  9.,  6.,  7.,  9.,  8., 10.],
        [60.,  5.,  6.,  0.,  7.,  6.,  5., 10., 10.,  9.],
        [42.,  8.,  7.,  6.,  7.,  7.,  7., 10., 10., 10.],
        [19.,  7.,  7.,  6., 10.,  7.,  7.,  9.,  8., 10.],
        [ 7.,  9.,  9.,  8.,  8.,  8.,  9., 10., 10., 10.],
        [37.,  9.,  7.,  0.,  8.,  7.,  

In [37]:

# Creating the architecture of the Neural Network
class SAE(nn.Module):
    def __init__(self, ):
        super(SAE, self).__init__()
        self.fc1 = nn.Linear(nb_courses, 20)
        self.fc2 = nn.Linear(20, 10)
        self.fc3 = nn.Linear(10, 20)
        self.fc4 = nn.Linear(20, nb_courses)
        self.activation = nn.Sigmoid()
    def forward(self, x):
        x = self.activation(self.fc1(x))
        x = self.activation(self.fc2(x))
        x = self.activation(self.fc3(x))
        x = self.fc4(x)
        return x
sae = SAE()
criterion = nn.MSELoss()
optimizer = optim.RMSprop(sae.parameters(), lr = 0.01, weight_decay = 0.5)
`

In [39]:
# Training the SAE
nb_epoch = 200
for epoch in range(1, nb_epoch + 1):
    train_loss = 0
    s = 0.
    for id_user in range(nb_students):
        input = Variable(training_set[id_user]).unsqueeze(0)
        target = input.clone()
        if torch.sum(target.data > 0) > 0:
            output = sae(input)
            target.require_grad = False
            output[target == 0] = 0
            loss = criterion(output, target)
            mean_corrector = nb_courses/float(torch.sum(target.data > 0) + 1e-10)
            loss.backward()
            train_loss += np.sqrt(loss.data[0]*mean_corrector)
            s += 1.
            optimizer.step()
    print('epoch: '+str(epoch)+' loss: '+str(train_loss/s))


RuntimeError: size mismatch, m1: [1 x 10], m2: [9 x 20] at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/TH/generic/THTensorMath.cpp:136

In [70]:
class RBM():
    def __init__(self, nv, nh):
        self.W = torch.randn(nh, nv)
        self.a = torch.randn(1, nh)
        self.b = torch.randn(1, nv)

    def sample_h(self, x):
        wx = torch.mm(x, self.W.t())
        activation = wx + self.a.expand_as(wx)
        p_h_given_v = torch.sigmoid(activation)
        return p_h_given_v, torch.bernoulli(p_h_given_v)

    def sample_v(self, y):
        wy = torch.mm(y, self.W)
        activation = wy + self.b.expand_as(wy)
        p_v_given_h = torch.sigmoid(activation)
        return p_v_given_h, torch.bernoulli(p_v_given_h)

    def train(self, v0, vk, ph0, phk):
        self.W += torch.mm(v0.t(), ph0) - torch.mm(vk.t(), phk)
        self.b += torch.sum((v0 - vk), 0)
        self.a += torch.sum((ph0 - phk), 0)

In [73]:
nv = len(training_set[0])
nh = 19
batch_size = 31
rbm = RBM(nv, nh)

In [74]:
nb_users  = int(max(max(training_set[:,0]), max(test_set[:,0])))
nb_epoch = 10
for epoch in range(1, nb_epoch + 1):
    train_loss = 0
    s = 0.
    for id_user in range(0, nb_users - batch_size, batch_size):
        vk = training_set[id_user:id_user+batch_size]
        v0 = training_set[id_user:id_user+batch_size]
        ph0,_ = rbm.sample_h(v0)
        for k in range(10):
            _,hk = rbm.sample_h(vk)
            _,vk = rbm.sample_v(hk)
            vk[v0<0] = v0[v0<0]
        phk,_ = rbm.sample_h(vk)
        rbm.train(v0, vk, ph0, phk)
        train_loss += torch.mean(torch.abs(v0[v0>=0] - vk[v0>=0]))
        s += 1
        print('epoch: '+str(epoch)+' loss: '+str(train_loss/s))

epoch: 1 loss: tensor(32.9491)
epoch: 2 loss: tensor(32.6197)
epoch: 3 loss: tensor(32.6078)
epoch: 4 loss: tensor(32.6078)
epoch: 5 loss: tensor(32.6078)
epoch: 6 loss: tensor(32.6078)
epoch: 7 loss: tensor(32.6078)
epoch: 8 loss: tensor(32.6078)
epoch: 9 loss: tensor(32.6078)
epoch: 10 loss: tensor(32.6078)


In [75]:
test_loss = 0
s = 0.
for id_user in range(nb_users):
    v = training_set[id_user:id_user+1]
    vt = test_set[id_user:id_user+1]
    if len(vt[vt>=0]) > 0:
        _,h = rbm.sample_h(v)
        _,v = rbm.sample_v(h)
        test_loss += torch.mean(torch.abs(vt[vt>=0] - v[vt>=0]))
        s += 1.
print('test loss: '+str(test_loss/s))

IndexError: The shape of the mask [1, 19] at index 0 does not match the shape of the indexed tensor [0, 19] at index 0

In [77]:
vt

tensor([[62., 28.,  5., 33.,  0., 26.,  0., 94., 10., 94., 10., 23.,  5., 77.,
          7., 31.,  5., 63.,  6.]])

In [54]:
_,v

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1.]]), tensor([], size=(0, 19)))

In [56]:
vt

tensor([], size=(0, 19))